# vouch config
# bare minimum to get vouch running with google

vouch:
  domains:
    - cadams.io
  
oauth:
  provider: google
  # get credentials from...
  # https://console.developers.google.com/apis/credentials
  client_id: ***
  client_secret: ***
  callback_urls: 
    - https://login.cadams.io/auth
  preferredDomain: cadams.io
  # endpoints set from https://godoc.org/golang.org/x/oauth2/google
